# We need to create these classes for our project since it's specific to our problem statement
# pass is same as ...


class DataIngestionConfig:
    pass

class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...
class ModelEvaluationConfig:...
class ModelPusherConfig:...

